name: Node CI Build

on:
  push:
    branches: ["main", "dev", "feature**"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: windows-latest

    env:
      node-version: 18.x

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Version ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Check Prettier Format
        run: npm run format:check --if-present

      - name: Check ESLint Rules
        run: npm run lint --if-present

      - name: Build Application
        run: npm run build --if-present

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-build
          path: dist

      - name: Test Application with Coverage Report
        run: npm run test:coverage --if-present

      - name: Upload Coverage Report Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-coverage
          path: coverage

  deploy-coverage:
    needs: build

    runs-on: windows-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy App to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ github.event.repository.name }}-coverage
