name: Github CI Cleanup

on: workflow_dispatch

jobs:
  cleanup:
    name: Cleanup Workflow Runs
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Retrieve Latest Release
        uses: actions/github-script@v7
        id: cleanup_workflow_runs
        with:
          script: |
            const scriptPath = '${{ github.workspace }}/.github/scripts/cleanup-workflow-runs.js';
            const { default: cleanupWorkflowRuns } = await import(scriptPath);
            await cleanupWorkflowRuns({ core, context, github });