name: Node CI Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy App to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ github.event.repository.name }}-build

