name: GitHub CI Release

on:
  # workflow_run:
  #   workflows: ["Node CI Build"]
  #   types: ["completed"]
  #   branches: ["main", "dev", "feature**"]
  push:
    branches: ["main", "dev", "feature**"]

jobs:
  release:
    name: Release Application
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository ${{ github.event.repository.name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve Latest Release
        uses: actions/github-script@v7
        id: retrieve_latest_release
        with:
          script: |
            const scriptPath = '${{ github.workspace }}/.github/scripts/retrieve-latest-release.js';
            const { default: retrieveLatestRelease } = await import(scriptPath);
            await retrieveLatestRelease({ core, context, github });

      - name: Upload Release Asset
        uses: actions/github-script@v7
        id: upload_release_asset
        with:
          script: |
            const scriptPath = '${{ github.workspace }}/.github/scripts/upload-release-asset.js';
            const release = ${{ steps.retrieve_latest_release.outputs.release }};
            const { default: uploadReleaseAsset } = await import(scriptPath);
            await uploadReleaseAsset({ core, context, github, release });

      # - name: Publish Draft Release
      #   uses: actions/github-script@v7
      #   id: publish_draft_release
      #   if: ${{ steps.create_draft_release.outputs.released == 'true' }}
      #   with:
      #     script: |
      #       const scriptPath = '${{ github.workspace }}/.github/scripts/publish-draft-release.js';
      #       const release = ${{ toJson(steps.create_draft_release.outputs) }};
      #       const { default: publishDraftRelease } = await import(scriptPath);
      #       await publishDraftRelease({ core, context, github, release });
