name: GitHub CI Release

on:
  # pull_request:
  #   types: ["closed"]
  #   branches: ["main"]
  push:
    branches: ["feature**"]

jobs:
  release:
    name: Release Application
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository ${{ github.event.repository.name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Application
        uses: actions/github-script@v7
        id: release_app
        with:
          script: |
            const { default: releaseApp } = await import('${{ github.workspace }}/.github/scripts/release-app.js');
            await releaseApp({ core, context });
