name: GitHub CI Release

on:
  # pull_request:
  #   types: ["closed"]
  #   branches: ["main"]
  push:
    branches: ["feature**"]

jobs:
  release:
    name: Release Application
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository ${{ github.event.repository.name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: actions/github-script@v7
        id: create_release
        with:
          script: |
            const { default: createRelease } = await import('${{ github.workspace }}/.github/scripts/create-release.js');
            await createRelease({ core, context, github });

      - name: Upload Release Asset
        uses: actions/github-script@v7
        id: upload_release_asset
        with:
          script: |
            const { default: uploadReleaseAsset } = await import('${{ github.workspace }}/.github/scripts/upload-release-asset.js')
            await uploadReleaseAsset({ core, context, github });
